apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmsingle-main-b
  namespace: vm
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: gp3
  volumeMode: Filesystem
  volumeName: pvc-7ed503e8-181b-4b8b-ae62-1ba4b4ce3ffe
